### ISSUE TITLE
SDF Parser only works with double apostrophes in XML

### ISSUE THREAD

**Issue by roboticlemon** [urobosim/URoboSim#31]
Parser will fail if using single apostrophes in your .sdf, which is the default of gz sdf converter.

Eg. `<model name='robot'>` fails parsing
but `<model name="robot">` succeeds

Quick fix for users is to search and replace all single apostrophes and replace with double.

PS: This project is absolutely fantastic, keep up the great work!

**Comment by NeumannM89** [comment]
Thanks for pointing it out. I added a command to convert the ' with " to the readme.

**Comment by NeumannM89** [comment]
Should work without the conversion now
